DROP DATABASE IF EXISTS LISTA04;
CREATE DATABASE LISTA04;
USE LISTA04;

CREATE TABLE endereco (
	id DOUBLE PRIMARY KEY AUTO_INCREMENT,
	rua VARCHAR(60),
    numero VARCHAR(11),
    bairro VARCHAR(60)
);

CREATE TABLE PESSOA (
	id DOUBLE PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(60),
    cpf VARCHAR(11) UNIQUE,
    endereco_id double,
    CONSTRAINT endereco_id FOREIGN KEY (endereco_id)
    REFERENCES endereco(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO ENDERECO (RUA, NUMERO, BAIRRO) VALUES ('AAAAA', 'BBBBB', 'CCCCC');
INSERT INTO PESSOA (NOME, CPF, ENDERECO_ID) VALUES ('FELIPE', '12345678910', 1);

INSERT INTO ENDERECO (RUA, NUMERO, BAIRRO) VALUES ('DDDDD', 'EEEEE', 'FFFFF');
INSERT INTO PESSOA (NOME, CPF, ENDERECO_ID) VALUES ('JOAO', '12345678911', 2);

INSERT INTO ENDERECO (RUA, NUMERO, BAIRRO) VALUES ('IIIIII', 'HHHHHH', 'GGGGG');
INSERT INTO PESSOA (NOME, CPF, ENDERECO_ID) VALUES ('CARLOS', '12345678912', 3);

INSERT INTO ENDERECO (RUA, NUMERO, BAIRRO) VALUES ('JJJJJ', 'KKKKKB', 'LLLLL');
INSERT INTO PESSOA (NOME, CPF, ENDERECO_ID) VALUES ('PEDRO', '12345678913', 4);

INSERT INTO ENDERECO (RUA, NUMERO, BAIRRO) VALUES ('MMMMM', 'NNNNN', 'OOOOO');
INSERT INTO PESSOA (NOME, CPF, ENDERECO_ID) VALUES ('JULIANOLIXO', '12345678914', 5);

INSERT INTO ENDERECO (RUA, NUMERO, BAIRRO) VALUES ('PPPPP', 'QQQQQ', 'RRRRR');
INSERT INTO PESSOA (NOME, CPF, ENDERECO_ID) VALUES ('LIXO P KRL', '12345678915', 6);

